version: 2.1
jobs:
  build:
     docker: 
       - image: circleci/node:10
     steps:
       - checkout
       - run:
           name: dependencies instalation 
           command: |
               npm install --save
       - run:
           name: building project
           command: |
               npm run build
       
