version: 2.1
jobs:
  run_tests:
     docker: 
       - image: circleci/node:10
     steps:
       - checkout
       - run:
           name: dependencies instalation 
           command: |
               npm install --save
       - run:
           name: building project
           command: |
               npm run build
       - save_cache:
          key: v1-npm
          paths:
            - node_modules/
  workflow:
     build_test:
        jobs:
          - run_tests
