version: 2.1
jobs:
  run_tests:
     docker: 
       - image: circleci/node:10
     steps:
       - checkout
       - run:
           name: dependencies instalation 
           command: |
               npm install --save
  workflow:
     build_test:
        jobs:
          - run_tests
